### ISSUE TITLE
Use same approach for imageOverlay

### ISSUE THREAD

**Issue by navilaufm** [frogcat/leaflet-tilelayer-colorpicker#4]
The functionality of this plugin is perfect, as with the elevation example it easy to get and show an aprox. raster pixel value or range based on the color scale. Is there a way to do the same with imageOverlay, as in my case data is not as big or needed to tile as is simple imageOverlay on top of a leaflet map. Or any suggestion of another option / plugin ?

Specifically will like to extract values of color for a map like the following
![image](https://user-images.githubusercontent.com/61478833/187014838-fcbb999d-0ee2-4c1f-b3b3-abe62f5c6486.png)

**Comment by frogcat** [comment]
Color picker for [L.ImageOverlay](https://leafletjs.com/reference.html#imageoverlay) is easy and simple.
Try bellow.

Code <https://gist.github.com/frogcat/8836922bcaa17728bad05276efe7f99f>
Demo <https://bl.ocks.org/frogcat/raw/8836922bcaa17728bad05276efe7f99f/?raw=true>

**Comment by navilaufm** [comment]
Perfect. Thank you very much.

**Comment by navilaufm** [comment]
Great contribution 👍
